name: Full Stack CI Pipeline

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  # ==========================================
  # FRONTEND
  # ==========================================
  frontend-ci:
    name: Angular Validation
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Install dependencies
        run: npm ci
        working-directory: ui
        
      - name: Check Formatting
        run: npm run format:check
        working-directory: ui
        
      - name: Lint & Static Analysis
        run: npm run lint
        working-directory: ui
        
      - name: Unit Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless
        working-directory: ui
        
      - name: Integration Tests
        run: npm run test:integration
        working-directory: ui

  # ==========================================
  #.NET JOB
  # ==========================================
  backend-ci:
    name: .NET Validation
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Check Formatting
        # Fails the build if code deviates from .editorconfig styles
        run: dotnet format whitespace --verify-no-changes

      - name: Lint & Static Analysis (Analyzers)
        # Catches code smells and style violations
        run: dotnet format analyzers --verify-no-changes

      - name: Build with Strict Warnings
        # Compiles the code and treats warnings as errors to enforce strict static analysis
        run: dotnet build --no-restore -warnaserror

      - name: Unit Tests
        # Executes tests decorated with [Trait("Category", "Unit")]
        run: dotnet test --no-build --verbosity normal --filter "Category=Unit" --logger trx --results-directory "TestResults/Unit"

      - name: Integration Tests
        # Executes tests decorated with [Trait("Category", "Integration")]
        run: dotnet test --no-build --verbosity normal --filter "Category=Integration" --logger trx --results-directory "TestResults/Integration"
      
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        # Ensures test results are published even if the tests fail
        if: ${{ always() }}
        with:
          name: dotnet-test-results
          path: TestResults
